name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t freeleetcodecamp .

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Install AWS CLI and Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        sudo apt-get install -y zip

        # Download and install EB CLI
        wget https://elasticbeanstalk.amazonaws.com/downloads/ebcli/2.21.0/ebcli-bundle-2.21.0.zip -O ebcli-bundle.zip
        unzip ebcli-bundle.zip
        sudo ./ebcli-bundle/install -b ~/eb
        export PATH=$PATH:~/eb/bin
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Create Elastic Beanstalk Version
      run: eb create ${{ github.sha }} --label ${{ github.sha }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v17
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-north-1
        application_name: freeleetcodecamp
        environment_name: Freeleetcodecamp-env
        version_label: ${{ github.sha }}

